#! /usr/bin/env python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 110borwein_2019
## File description:
## 110borwein_2019
##

import sys
from src.error_handling.error_handler import error_handler
from src.error_handling.usage import usage
from src.solve_borwein_integral_for_n import solve_borwein_integral_for_n
from lib.is_integer import is_integer

def main(ac: int, av: list):
    if ac != 2:
        error_handler()
    if av[1] == "-h":
        usage()
        return 0
    if is_integer(av[1]) is False:
        print("/!\ Error report /!\\\n "
            "-> Given argument is not an integer.\n")
        error_handler()
    n = int(av[1])
    if n < 0:
        print("/!\ Error report /!\\\n "
            "-> Given argument is not in the Borwein's integral range [0 ; +Inf[.\n")
        error_handler()
    return solve_borwein_integral_for_n(n)

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv))